### ISSUE TITLE
xesmf no longer imported into interpolation module. 

### ISSUE THREAD

**Issue by imcslatte** [xoceanmodel/xroms#37]
After the last update to XROMS, the interpolation module no longer works for horizontal interpolation. But rather errors with the message:
 
NameError: name 'xe' is not defined

in interp.py.

It looks as though the module import for xesmf is commented out.

**Comment by kthyng** [comment]
Thanks @imcslatte! I've recently put out a new version to PyPI (v0.2.4, still coming through on conda-forge). Please check to see if this issue is still present in the new version so that over time we can work to address these. Thanks!

**Comment by imcslatte** [comment]
This issue seems to be fixed.

**Comment by kthyng** [comment]
Excellent, thanks @imcslatte!
