### ISSUE TITLE
Release on pypi and conda-forge?

### ISSUE THREAD

**Issue by rsignell-usgs** [xoceanmodel/xroms#39]
Would be nice to be able to conda install xroms from conda-forge.   

Any interest in releasing on pypi?

If released on pypi we could then use https://github.com/conda/grayskull to create the conda-forge recipe...

**Comment by kthyng** [comment]
Hey @rsignell-usgs! v0.2.4 is now available on PyPI and will be available through conda-forge once it [makes its way through the system](https://github.com/conda-forge/staged-recipes/pull/22900). I'll close this issue in anticipation of that. Thanks!
