### ISSUE TITLE
roms_dataset function issue

### ISSUE THREAD

**Issue by kyle-hinson** [xoceanmodel/xroms#53]
Came across this problem when trying to load in a normal output NetCDF file. Currently I try to apply xroms to my dataset loaded in with xarray and get no error message before python kills the application.

`file = 'roms_his.nc'`
`ds = xarray.open_dataset(file)`
`ds = xroms.roms_dataset(ds)`

I stepped through the roms_dataset function line by line and am first encountering an issue on line 511 which is calculating dz_w with:

`ds["dz_w"] = xgrid.diff(ds.z_rho, "Z", boundary="fill")`

The variable z_rho is present in the dataset and appears to be calculated normally, so I'm not sure why the diff command works above on line 503 to calculate dz and not below for dz_w.

--------------------------------------------------------------------------------------------------------------------------
Turns out that I missed specifying chunking originally, doing so fixes my issue

`ds = xarray.open_dataset(files[0], chunks={'ocean_time': 1})`
`ds = xroms.roms_dataset(ds)`

**Comment by kthyng** [comment]
@kyle-hinson Ok thank you for the update!
